server:
  port: 8082

logging:
  file:
    name: logs/erp-product.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 7

spring:
  application:
    name: erp-product
  datasource:
    url: jdbc:mysql://localhost:3306/erp_jp_crossborder?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: erp_app
    password: Erp_Jp_2026!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
